// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const changeUserWithMostCancle = `-- name: ChangeUserWithMostCancle :exec
UPDATE "profile"
SET last_name = 'Redington'
WHERE user_id = (
SELECT cr.user_id
FROM "change_reservation" cr
WHERE cr.from_status NOT IN ('CANCELED', 'CANCELED-BY-TIME')
    AND cr.to_status = 'CANCELED'
GROUP BY cr.user_id
ORDER BY COUNT(cr.id) DESC
LIMIT 1
)
`

func (q *Queries) ChangeUserWithMostCancle(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, changeUserWithMostCancle)
	return err
}

const deleteAllCancledTicket = `-- name: DeleteAllCancledTicket :exec
DELETE FROM "reservation" re
WHERE re.status IN ('CANCELED', 'CANCELED-BY-TIME')
`

func (q *Queries) DeleteAllCancledTicket(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCancledTicket)
	return err
}

const deleteRedingtonTicket = `-- name: DeleteRedingtonTicket :exec
DELETE FROM "reservation" r
WHERE r.user_id = (SELECT pro.user_id FROM "profile" pro
WHERE pro.last_name = 'Redington'
LIMIT 1) AND r.status IN ('CANCELED', 'CANCELED-BY-TIME')
`

func (q *Queries) DeleteRedingtonTicket(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRedingtonTicket)
	return err
}

const getAdminName = `-- name: GetAdminName :many
SELECT 
    u.id,
    CONCAT(pro.first_name, ' ', pro.last_name) AS full_name
FROM "user" u
INNER JOIN "profile" pro ON u.id = pro.user_id
WHERE u.role = 'ADMIN'
ORDER BY u.id
`

type GetAdminNameRow struct {
	ID       int64       `json:"id"`
	FullName interface{} `json:"full_name"`
}

func (q *Queries) GetAdminName(ctx context.Context) ([]GetAdminNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getAdminName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminNameRow{}
	for rows.Next() {
		var i GetAdminNameRow
		if err := rows.Scan(&i.ID, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminWithMostReject = `-- name: GetAdminWithMostReject :one
 WITH canceled_changes AS (
    SELECT 
        cr.admin_id, 
        CONCAT(pro.first_name, ' ', pro.last_name) AS full_name,
        COUNT(cr.id) AS cancel_count
    FROM change_reservation cr
    INNER JOIN "profile" pro ON pro.user_id = cr.admin_id
    WHERE cr.from_status NOT IN ('CANCELED', 'CANCELED-BY-TIME')
        AND cr.to_status = 'CANCELED'
    GROUP BY cr.admin_id, pro.first_name, pro.last_name
),
total_canceled AS (
    SELECT COUNT(*) AS total FROM change_reservation
    WHERE from_status NOT IN ('CANCELED', 'CANCELED-BY-TIME')
        AND to_status = 'CANCELED'
)
SELECT 
cc.admin_id,
cc.full_name,
cc.cancel_count AS "NO. of Cancellations",
ROUND((cc.cancel_count::decimal / tc.total) * 100, 2) AS "Cancellation Percentage"
FROM canceled_changes cc, total_canceled tc
ORDER BY cc.cancel_count DESC
LIMIT 1
`

type GetAdminWithMostRejectRow struct {
	AdminID                sql.NullInt64 `json:"admin_id"`
	FullName               interface{}   `json:"full_name"`
	NOOfCancellations      int64         `json:"NO. of Cancellations"`
	CancellationPercentage string        `json:"Cancellation Percentage"`
}

func (q *Queries) GetAdminWithMostReject(ctx context.Context) (GetAdminWithMostRejectRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminWithMostReject)
	var i GetAdminWithMostRejectRow
	err := row.Scan(
		&i.AdminID,
		&i.FullName,
		&i.NOOfCancellations,
		&i.CancellationPercentage,
	)
	return i, err
}

const getCityWithOldestUser = `-- name: GetCityWithOldestUser :many
SELECT 
    u.id, 
    CONCAT(oc.province, '  (', oc.county, ')') AS origin
FROM "user" u
INNER JOIN "reservation" re ON u.id = re.user_id
INNER JOIN "payment" pa ON pa.id = re.payment_id
INNER JOIN "ticket" t ON re.ticket_id = t.id
INNER JOIN "route" ro ON t.route_id = ro.id
INNER JOIN "city" oc ON oc.id = ro.origin_city_id
WHERE u.id = (SELECT u.id FROM "user" u 
WHERE u.role = 'USER'
ORDER BY u.created_at DESC 
LIMIT 1) AND pa.status = 'COMPLETED'
GROUP BY u.id, oc.province, oc.county
`

type GetCityWithOldestUserRow struct {
	ID     int64       `json:"id"`
	Origin interface{} `json:"origin"`
}

func (q *Queries) GetCityWithOldestUser(ctx context.Context) ([]GetCityWithOldestUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getCityWithOldestUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCityWithOldestUserRow{}
	for rows.Next() {
		var i GetCityWithOldestUserRow
		if err := rows.Scan(&i.ID, &i.Origin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountOfTicketFromTehran = `-- name: GetCountOfTicketFromTehran :many
SELECT 
    oc.county AS origin,
    CONCAT(dc.province, '  (', dc.county, ')') AS destination,
    COUNT(dc.county) AS "tripNO."
FROM "ticket" t
INNER JOIN "reservation" re ON t.id = re.ticket_id
INNER JOIN "route" ro ON t.route_id = ro.id
INNER JOIN "city" oc ON oc.id = ro.origin_city_id
INNER JOIN "city" dc ON dc.id = ro.destination_city_id
WHERE oc.county = 'Tehran'
GROUP BY oc.county, dc.province, dc.county
`

type GetCountOfTicketFromTehranRow struct {
	Origin      string      `json:"origin"`
	Destination interface{} `json:"destination"`
	TripNO      int64       `json:"tripNO."`
}

func (q *Queries) GetCountOfTicketFromTehran(ctx context.Context) ([]GetCountOfTicketFromTehranRow, error) {
	rows, err := q.db.QueryContext(ctx, getCountOfTicketFromTehran)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCountOfTicketFromTehranRow{}
	for rows.Next() {
		var i GetCountOfTicketFromTehranRow
		if err := rows.Scan(&i.Origin, &i.Destination, &i.TripNO); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountOfTicketVehicle = `-- name: GetCountOfTicketVehicle :many
SELECT 
    t.vehicle_type, 
    COUNT(t.id) AS "NO." 
FROM "ticket" t
INNER JOIN "reservation" r ON r.ticket_id = t.id
INNER JOIN "payment" p ON p.id = r.payment_id
WHERE p.status = 'COMPLETED'
GROUP BY t.vehicle_type
ORDER BY "NO." DESC
`

type GetCountOfTicketVehicleRow struct {
	VehicleType VehicleType `json:"vehicle_type"`
	NO          int64       `json:"NO."`
}

func (q *Queries) GetCountOfTicketVehicle(ctx context.Context) ([]GetCountOfTicketVehicleRow, error) {
	rows, err := q.db.QueryContext(ctx, getCountOfTicketVehicle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCountOfTicketVehicleRow{}
	for rows.Next() {
		var i GetCountOfTicketVehicleRow
		if err := rows.Scan(&i.VehicleType, &i.NO); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReport = `-- name: GetReport :many
SELECT 
    res.ticket_id, 
    res.id AS reservation_id,
    repo.request_type, 
    repo.request_text, 
    repo.response_text, 
    sub.rep_count AS rep_count
FROM "reservation" res
INNER JOIN "report" repo ON res.id = repo.reservation_id
INNER JOIN (
    SELECT 
        t.id,
        COUNT(t.id) AS rep_count
    FROM "ticket" t
    INNER JOIN "reservation" re ON re.ticket_id = t.id
    INNER JOIN "report" rep ON rep.reservation_id = re.id
    GROUP BY t.id
    ORDER BY t.id
    LIMIT 1) sub ON res.ticket_id = sub.id
`

type GetReportRow struct {
	TicketID      int64       `json:"ticket_id"`
	ReservationID int64       `json:"reservation_id"`
	RequestType   RequestType `json:"request_type"`
	RequestText   string      `json:"request_text"`
	ResponseText  string      `json:"response_text"`
	RepCount      int64       `json:"rep_count"`
}

func (q *Queries) GetReport(ctx context.Context) ([]GetReportRow, error) {
	rows, err := q.db.QueryContext(ctx, getReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReportRow{}
	for rows.Next() {
		var i GetReportRow
		if err := rows.Scan(
			&i.TicketID,
			&i.ReservationID,
			&i.RequestType,
			&i.RequestText,
			&i.ResponseText,
			&i.RepCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSecondPopularTicketInfo = `-- name: GetSecondPopularTicketInfo :one
SELECT 
t.id, 
t.vehicle_type, 
CONCAT(oc.province, '  (', oc.county, ')') AS origin,
CONCAT(dc.province, '  (', dc.county, ')') AS destination,
COUNT(r.id) AS "NO." FROM "change_reservation" cr
INNER JOIN "reservation" r ON cr.reservation_id = r.id
INNER JOIN "ticket" t ON t.id = r.ticket_id
INNER JOIN "route" ro ON t.route_id = ro.id
INNER JOIN "city" oc ON oc.id = ro.origin_city_id
INNER JOIN "city" dc ON dc.id = ro.destination_city_id
WHERE cr.to_status = 'RESERVED'
GROUP BY t.id, t.vehicle_type, oc.province, oc.county, dc.province, dc.county
ORDER BY "NO."
LIMIT 1
OFFSET 1
`

type GetSecondPopularTicketInfoRow struct {
	ID          int64       `json:"id"`
	VehicleType VehicleType `json:"vehicle_type"`
	Origin      interface{} `json:"origin"`
	Destination interface{} `json:"destination"`
	NO          int64       `json:"NO."`
}

func (q *Queries) GetSecondPopularTicketInfo(ctx context.Context) (GetSecondPopularTicketInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getSecondPopularTicketInfo)
	var i GetSecondPopularTicketInfoRow
	err := row.Scan(
		&i.ID,
		&i.VehicleType,
		&i.Origin,
		&i.Destination,
		&i.NO,
	)
	return i, err
}

const getSumOfPaymentInDifferentMonth = `-- name: GetSumOfPaymentInDifferentMonth :many
SELECT 
    u.id, 
    CONCAT(pro.first_name, ' ', pro.last_name) AS full_name,
    TO_CHAR(pa.created_at, 'YYYY-MM') AS payment_month,
    SUM(pa.amount) AS total_amount
FROM "user" u 
INNER JOIN "reservation" r ON u.id = r.user_id
LEFT JOIN "payment" pa ON r.payment_id = pa.id
JOIN "profile" pro ON u.id = pro.user_id
GROUP BY u.id, pro.first_name, pro.last_name, TO_CHAR(pa.created_at, 'YYYY-MM')
HAVING SUM(pa.amount) IS NOT NULL
ORDER BY u.id, payment_month
`

type GetSumOfPaymentInDifferentMonthRow struct {
	ID           int64       `json:"id"`
	FullName     interface{} `json:"full_name"`
	PaymentMonth string      `json:"payment_month"`
	TotalAmount  int64       `json:"total_amount"`
}

func (q *Queries) GetSumOfPaymentInDifferentMonth(ctx context.Context) ([]GetSumOfPaymentInDifferentMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getSumOfPaymentInDifferentMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSumOfPaymentInDifferentMonthRow{}
	for rows.Next() {
		var i GetSumOfPaymentInDifferentMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.PaymentMonth,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreeUsersWithMostPurchaseInWeek = `-- name: GetThreeUsersWithMostPurchaseInWeek :many
SELECT 
u.id, 
CONCAT(pro.first_name, ' ', pro.last_name) AS full_name, 
COUNT(re.id) AS "NO."
FROM "user" u
INNER JOIN "profile" pro ON u.id = pro.user_id
INNER JOIN "reservation" re ON u.id = re.user_id
INNER JOIN "payment" pa ON pa.id = re.payment_id
WHERE pa.status = 'COMPLETED' AND pa.created_at > NOW() - INTERVAL '7 days'
GROUP BY u.id, pro.first_name, pro.last_name
ORDER BY "NO." DESC
LIMIT 3
`

type GetThreeUsersWithMostPurchaseInWeekRow struct {
	ID       int64       `json:"id"`
	FullName interface{} `json:"full_name"`
	NO       int64       `json:"NO."`
}

func (q *Queries) GetThreeUsersWithMostPurchaseInWeek(ctx context.Context) ([]GetThreeUsersWithMostPurchaseInWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, getThreeUsersWithMostPurchaseInWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThreeUsersWithMostPurchaseInWeekRow{}
	for rows.Next() {
		var i GetThreeUsersWithMostPurchaseInWeekRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.NO); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketInfoForToday = `-- name: GetTicketInfoForToday :many
SELECT 
    u.id,
    CONCAT(pro.first_name, ' ', pro.last_name) AS full_name, 
    t.id AS "ticket id",
    t.vehicle_type,
    TO_CHAR(pa.created_at, 'YYYY-MM-DD HH24:MI:SS') AS issued
FROM "user" u
INNER JOIN "profile" pro ON u.id = pro.user_id
INNER JOIN "reservation" r ON u.id = r.user_id
INNER JOIN "ticket" t ON  t.id = r.ticket_id
INNER JOIN "payment" pa ON  pa.id = r.payment_id
WHERE pa.status = 'COMPLETED' AND pa.created_at >= date_trunc('day', now())
ORDER BY pa.created_at
`

type GetTicketInfoForTodayRow struct {
	ID          int64       `json:"id"`
	FullName    interface{} `json:"full_name"`
	TicketID    int64       `json:"ticket id"`
	VehicleType VehicleType `json:"vehicle_type"`
	Issued      string      `json:"issued"`
}

func (q *Queries) GetTicketInfoForToday(ctx context.Context) ([]GetTicketInfoForTodayRow, error) {
	rows, err := q.db.QueryContext(ctx, getTicketInfoForToday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTicketInfoForTodayRow{}
	for rows.Next() {
		var i GetTicketInfoForTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.TicketID,
			&i.VehicleType,
			&i.Issued,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInfoWithNewTicket = `-- name: GetUserInfoWithNewTicket :one
SELECT 
    u.id,
    CONCAT(pro.first_name, ' ', pro.last_name) AS full_name,
    TO_CHAR(pa.created_at, 'YYYY-MM-DD	HH24:MI:SS') AS "created at"
FROM "user" u
INNER JOIN "profile" pro ON u.id = pro.user_id
INNER JOIN "reservation" re ON u.id = re.user_id
INNER JOIN "ticket" t ON re.ticket_id = t.id
INNER JOIN "payment" pa ON pa.id = re.payment_id
WHERE pa.status = 'COMPLETED'
ORDER BY pa.created_at DESC
LIMIT 1
`

type GetUserInfoWithNewTicketRow struct {
	ID        int64       `json:"id"`
	FullName  interface{} `json:"full_name"`
	CreatedAt string      `json:"created at"`
}

func (q *Queries) GetUserInfoWithNewTicket(ctx context.Context) (GetUserInfoWithNewTicketRow, error) {
	row := q.db.QueryRowContext(ctx, getUserInfoWithNewTicket)
	var i GetUserInfoWithNewTicketRow
	err := row.Scan(&i.ID, &i.FullName, &i.CreatedAt)
	return i, err
}

const getUserMoreThanAmountAvrage = `-- name: GetUserMoreThanAmountAvrage :many
SELECT 
    u.id, 
    COALESCE(u.email, 'No Email') AS email, 
    COALESCE(u.phone_number, 'No Phone') AS phone_number, 
    SUM(p.amount) AS "total amount" FROM "user" u
INNER JOIN "reservation" r ON u.id = r.user_id
INNER JOIN "payment" p ON p.id = r.payment_id
GROUP BY u.id, u.email, u.phone_number
HAVING SUM(p.amount) > (SELECT AVG(p.amount) FROM "payment" p
    WHERE p.status = 'COMPLETED'
)
`

type GetUserMoreThanAmountAvrageRow struct {
	ID          int64  `json:"id"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
	TotalAmount int64  `json:"total amount"`
}

func (q *Queries) GetUserMoreThanAmountAvrage(ctx context.Context) ([]GetUserMoreThanAmountAvrageRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserMoreThanAmountAvrage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserMoreThanAmountAvrageRow{}
	for rows.Next() {
		var i GetUserMoreThanAmountAvrageRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PhoneNumber,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithAllVehicleRejected = `-- name: GetUserWithAllVehicleRejected :many
SELECT 
  u.id, 
    COALESCE(u.email, 'No Email') AS email, 
    COALESCE(u.phone_number, 'No Phone') AS phone_number
FROM "user" u
WHERE NOT EXISTS (
    SELECT t.vehicle_type
    FROM "ticket" t
    WHERE t.vehicle_type IN ('BUS', 'AIRPLANE', 'TRAIN')
    EXCEPT
    SELECT t.vehicle_type
    FROM "reservation" r
    INNER JOIN "ticket" t ON r.ticket_id = t.id
    INNER JOIN "payment" p ON r.payment_id = p.id
    WHERE r.user_id = u.id AND p.status = 'COMPLETED'
)
`

type GetUserWithAllVehicleRejectedRow struct {
	ID          int64  `json:"id"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
}

func (q *Queries) GetUserWithAllVehicleRejected(ctx context.Context) ([]GetUserWithAllVehicleRejectedRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWithAllVehicleRejected)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserWithAllVehicleRejectedRow{}
	for rows.Next() {
		var i GetUserWithAllVehicleRejectedRow
		if err := rows.Scan(&i.ID, &i.Email, &i.PhoneNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithLessThanTwoTicketVehicle = `-- name: GetUserWithLessThanTwoTicketVehicle :many
SELECT 
    u.id, 
    CONCAT(pro.first_name, ' ', pro.last_name) AS full_name, 
    t.vehicle_type,
    COUNT(r.ticket_id) AS ticket_count
FROM "user" u
INNER JOIN "profile" pro ON u.id = pro.user_id
INNER JOIN "reservation" r ON u.id = r.user_id
INNER JOIN "payment" pa ON pa.id = r.payment_id
INNER JOIN "ticket" t ON t.id = r.ticket_id
WHERE pa.status = 'COMPLETED'
GROUP BY u.id, pro.first_name, pro.last_name, t.vehicle_type
HAVING COUNT(r.ticket_id) < 3
ORDER BY u.id
`

type GetUserWithLessThanTwoTicketVehicleRow struct {
	ID          int64       `json:"id"`
	FullName    interface{} `json:"full_name"`
	VehicleType VehicleType `json:"vehicle_type"`
	TicketCount int64       `json:"ticket_count"`
}

func (q *Queries) GetUserWithLessThanTwoTicketVehicle(ctx context.Context) ([]GetUserWithLessThanTwoTicketVehicleRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWithLessThanTwoTicketVehicle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserWithLessThanTwoTicketVehicleRow{}
	for rows.Next() {
		var i GetUserWithLessThanTwoTicketVehicleRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.VehicleType,
			&i.TicketCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithMoreThanTwoTicket = `-- name: GetUserWithMoreThanTwoTicket :many
SELECT 
    u.id, 
    CONCAT(pro.first_name, ' ', pro.last_name) AS full_name, 
    u.role,
    COUNT(r.ticket_id) AS ticket_count
FROM "user" u
INNER JOIN "profile" pro ON u.id = pro.user_id
INNER JOIN "reservation" r ON u.id = r.user_id
INNER JOIN "payment" pa ON pa.id = r.payment_id
WHERE u.role != 'ADMIN' AND pa.status = 'COMPLETED'
GROUP BY u.id, pro.first_name, pro.last_name, u.role
HAVING COUNT(r.ticket_id) > 1
ORDER BY u.id
`

type GetUserWithMoreThanTwoTicketRow struct {
	ID          int64       `json:"id"`
	FullName    interface{} `json:"full_name"`
	Role        Role        `json:"role"`
	TicketCount int64       `json:"ticket_count"`
}

func (q *Queries) GetUserWithMoreThanTwoTicket(ctx context.Context) ([]GetUserWithMoreThanTwoTicketRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWithMoreThanTwoTicket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserWithMoreThanTwoTicketRow{}
	for rows.Next() {
		var i GetUserWithMoreThanTwoTicketRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Role,
			&i.TicketCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithOneTicketInCity = `-- name: GetUserWithOneTicketInCity :many
SELECT 
    u.id,
    CONCAT(pro.first_name, ' ', pro.last_name) AS full_name,
    CONCAT(dc.province, '  (', dc.county, ')') AS destination,
    COUNT(dc.county) AS "tripNO."
FROM "user" u
INNER JOIN "profile" pro ON u.id = pro.user_id
INNER JOIN "reservation" re ON u.id = re.user_id
INNER JOIN "ticket" t ON re.ticket_id = t.id
INNER JOIN "route" ro ON t.route_id = ro.id
INNER JOIN "city" oc ON oc.id = ro.origin_city_id
INNER JOIN "city" dc ON dc.id = ro.destination_city_id
GROUP BY u.id, pro.first_name, pro.last_name, dc.county, dc.province
HAVING COUNT(dc.county) = 1
ORDER BY u.id
`

type GetUserWithOneTicketInCityRow struct {
	ID          int64       `json:"id"`
	FullName    interface{} `json:"full_name"`
	Destination interface{} `json:"destination"`
	TripNO      int64       `json:"tripNO."`
}

func (q *Queries) GetUserWithOneTicketInCity(ctx context.Context) ([]GetUserWithOneTicketInCityRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWithOneTicketInCity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserWithOneTicketInCityRow{}
	for rows.Next() {
		var i GetUserWithOneTicketInCityRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Destination,
			&i.TripNO,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithTickets = `-- name: GetUserWithTickets :many
SELECT 
    u.id, 
    CONCAT(pro.first_name, ' ', pro.last_name) AS full_name, 
    u.role,
    COUNT(r.ticket_id) AS ticket_count
FROM "user" u
INNER JOIN "profile" pro ON u.id = pro.user_id
INNER JOIN "reservation" r ON u.id = r.user_id
INNER JOIN "payment" pa ON pa.id = r.payment_id
WHERE u.role != 'ADMIN' AND pa.status = 'COMPLETED'
GROUP BY u.id, pro.first_name, pro.last_name, u.role
HAVING COUNT(r.ticket_id) > 0
ORDER BY u.id
`

type GetUserWithTicketsRow struct {
	ID          int64       `json:"id"`
	FullName    interface{} `json:"full_name"`
	Role        Role        `json:"role"`
	TicketCount int64       `json:"ticket_count"`
}

func (q *Queries) GetUserWithTickets(ctx context.Context) ([]GetUserWithTicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserWithTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserWithTicketsRow{}
	for rows.Next() {
		var i GetUserWithTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Role,
			&i.TicketCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWithNoTickets = `-- name: GetUsersWithNoTickets :many
SELECT 
    u.id, 
    CONCAT(p.first_name, ' ', p.last_name) AS full_name, 
    u.role,
    COUNT(r.ticket_id) AS ticket_count
FROM "user" u
LEFT JOIN "reservation" r ON u.id = r.user_id
JOIN "profile" p ON u.id = p.user_id
WHERE u.role != 'ADMIN'
GROUP BY u.id, p.first_name, p.last_name, u.role, r.status
HAVING COUNT(r.ticket_id) = 0
ORDER BY u.id
`

type GetUsersWithNoTicketsRow struct {
	ID          int64       `json:"id"`
	FullName    interface{} `json:"full_name"`
	Role        Role        `json:"role"`
	TicketCount int64       `json:"ticket_count"`
}

func (q *Queries) GetUsersWithNoTickets(ctx context.Context) ([]GetUsersWithNoTicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersWithNoTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersWithNoTicketsRow{}
	for rows.Next() {
		var i GetUsersWithNoTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Role,
			&i.TicketCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upadateMahanAirTicketCost = `-- name: UpadateMahanAirTicketCost :exec
UPDATE "ticket"
SET amount = amount * 0.9
WHERE vehicle_id IN (
SELECT v.id FROM "vehicle" v
INNER JOIN "company" c ON v.company_id = c.id
WHERE c.name = 'Mahan Air'
)
`

func (q *Queries) UpadateMahanAirTicketCost(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, upadateMahanAirTicketCost)
	return err
}

const updateMahanAirPaymentCost = `-- name: UpdateMahanAirPaymentCost :exec
UPDATE "payment"
SET amount = amount * 0.9
WHERE id IN (
SELECT r.payment_id FROM "reservation" r
INNER JOIN "ticket" t ON r.ticket_id = t.id
INNER JOIN "vehicle" v ON t.vehicle_id = v.id
INNER JOIN "company" c ON c.id = v.company_id
WHERE c.name = 'Mahan Air'
)
`

func (q *Queries) UpdateMahanAirPaymentCost(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateMahanAirPaymentCost)
	return err
}
