version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    container_name: test_for_bilitioo_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bilitioo
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: test_for_bilitioo_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
